### ISSUE TITLE
Links Not Working After Editing Profile

### ISSUE THREAD

**Issue by jlaneve** [EmersonWalker/mplanner#23]
After you edit your profile, all links lead to dashboard.

**Comment by ryw** [comment]
Do all links go to dashboard, or just `/` and `/dashboard` ?

**Comment by jlaneve** [comment]
All links, as far as I have tested, go to /dashboard, and the calendar does
not show

**Comment by ryw** [comment]
try resetting `mrt reset` and sign in with user `demo@demo.com` password `demo` — are you signing in with Google? Maybe I broke that...

**Comment by jlaneve** [comment]
Still doesn't work. I tried updating meteor, mrt reset, and the demo account. Not signing in with Google, the button doesn't work.

**Comment by ryw** [comment]
Are you getting an error in the javascript console?

On Mon, Dec 2, 2013 at 7:32 PM, Julian LaNeve notifications@github.comwrote:

> Still doesn't work. I tried updating meteor, mrt reset, and the demo
> account. Not signing in with Google, the button doesn't work.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/EmersonWalker/mplanner/issues/23#issuecomment-29672981
> .

## 

-Ry

_Ry Walker_ | Partner at Differential http://differential.io |
513.417.2163 | @rywalker http://twitter.com/rywalker |
LinkedInhttp://www.linkedin.com/in/rywalker

**Comment by jlaneve** [comment]
No error. Does it work for you?

**Comment by ryw** [comment]
Yes I can click email address, it takes me back to profile. All the links
in the footer takes me to the pages I expect them to

On Mon, Dec 2, 2013 at 7:46 PM, Julian LaNeve notifications@github.comwrote:

> No error. Does it work for you?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/EmersonWalker/mplanner/issues/23#issuecomment-29673630
> .

## 

-Ry

_Ry Walker_ | Partner at Differential http://differential.io |
513.417.2163 | @rywalker http://twitter.com/rywalker |
LinkedInhttp://www.linkedin.com/in/rywalker

**Comment by jlaneve** [comment]
The link with the name works, but that will just bring you back to editing your profile.

**Comment by jlaneve** [comment]
The mPlanner link in the top left is what is not working. That will just bring me back to the dashboard

**Comment by ryw** [comment]
Yes that's intentional. Once you sign in, I'm sending the user to the
dashboard if they visit the homepage rather than the marketing page. Many
sites work this way - for example, go to github.com/ when signed in vs. not
signed in.

On Mon, Dec 2, 2013 at 7:53 PM, Julian LaNeve notifications@github.comwrote:

> The mPlanner link in the top left is what is not working. That will just
> bring me back to the dashboard
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/EmersonWalker/mplanner/issues/23#issuecomment-29674010
> .

## 

-Ry

_Ry Walker_ | Partner at Differential http://differential.io |
513.417.2163 | @rywalker http://twitter.com/rywalker |
LinkedInhttp://www.linkedin.com/in/rywalker
